import type { QuestionnaireTemplate } from "./types"

export const cyclingSurvey2025: QuestionnaireTemplate = {
  id: "cycling-survey-2025",
  title: "「環島自行車路線」使用情形及滿意度評鑑調查",
  description:
    "本評鑑調查目的在了解您曾經騎乘或本次騎乘「環島自行車路線」的感受及意見，做為後續路線規劃及改善參考，謝謝！",
  banner: "/banner-video/cycling-survey.mp4", // !! Video
  version: "1.0.0",
  organize: "交通部運輸研究所",
  isRepeatable: true,
  createdAt: "2025-07-03T00:00:00+08:00",
  updatedAt: "2025-07-03T00:00:00+08:00",
  // Route tracking configuration
  routeTracking: {
    enabled: true,
    routeSelectionQuestionId: "recent-route",
    trackSubmissionsByRoute: true
  },
  // Validation rules for route submissions
  validationRules: [
    {
      type: 'route_submission_limit',
      config: {
        maxSubmissionsPerRoute: 1,
        routeSelectionQuestionId: "recent-route"
      },
      enforcement: 'hide',
      errorMessage: '您已經填寫過此路線的評鑑調查，每條路線只能填寫一次',
      isActive: true
    },
    {
      type: 'route_completion_limit',
      config: {
        routeSelectionQuestionId: "recent-route"
      },
      enforcement: 'hide',
      errorMessage: '此路線已達到收集上限，無法再填寫',
      isActive: true
    }
  ],
  kmlCategory: ['round-island-main', 'round-island', 'round-island-alternative'], // Dynamic KML injection
  sections: [
    {
      id: "route-usage",
      title: "環島自行車路線騎乘情形",
      questions: [
        {
          id: "recent-route",
          type: "map",
          label: "請選擇一年內曾騎乘過的環島自行車路線",
          required: true,
          options: [], // Empty options array for map type
          defaultCenter: [23.8, 121.0],
          defaultZoom: 7,
          showLayerControl: true,
        },
        {
          id: "recent-route-date",
          type: "time",
          label: "最近一次騎乘該路線的時間",
          timeFormat: "YYYY-MM",
          required: true,
          minDate: "2023-01",
          maxDate: "2025-09",
        },
        {
          id: "route-purpose",
          type: "select-text",
          label: "該次旅程的目的",
          required: true,
          options: ["一鼓作氣環島", "分段環島", "休閒旅遊", "運動健身", "通勤通學", "其他"],
          textLabel: "其他目的",
          textPlaceholder: "請描述您的旅程目的",
          textMinLength: 2,
          textMaxLength: 50,
        },
        {
          id: "bike-source",
          type: "select-text",
          label: "自行車來源",
          required: true,
          options: ["自己的車", "旅行社提供", "飯店提供", "租賃", "親友借用", "其他"],
          textLabel: "其他來源",
          textPlaceholder: "請描述自行車來源",
          textMinLength: 2,
          textMaxLength: 50,
        },
        {
          id: "other-transport",
          type: "checkbox",
          label: "還使用哪些交通工具（可複選）",
          required: true,
          options: [
            "遊覽車",
            "火車",
            "汽車",
            "機車",
            "步行",
            "客運/公車",
            "計程車",
            "飛機",
            "船",
            "捷運",
            "高鐵",
            "未使用其他交通工具",
          ]
        },
      ],
    },
    {
      id: "continuity",
      title: "一、連續性",
      description: "請就您當次旅程體驗，填答下列各項設施及服務的滿意度：",
      questions: [
        {
          id: "route-sign",
          type: "radio",
          label: "本路線尋路/導引標誌標線",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "route-bridge",
          type: "radio",
          label: "橋梁或地下道的自行車騎乘動線",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "route-barrier",
          type: "radio",
          label: "本路線車阻設置形式及位置",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "route-continuity",
          type: "radio",
          label: "本路線整體騎乘動線的連續性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "continuity-issue",
          type: "region-long-answer",
          label: "您對騎乘動線感到連續性不佳的路段或地點及其原因為何？（非必填）",
          regions: [
            "新北市",
            "宜蘭縣",
            "花蓮縣",
            "臺東縣",
            "基隆市",
            "臺北市",
            "桃園市",
            "苗栗縣",
            "新竹縣",
            "新竹市",
            "臺中市",
            "彰化縣",
            "雲林縣",
            "南投縣",
            "嘉義縣",
            "嘉義市",
            "臺南市",
            "高雄市",
            "屏東縣",
            "澎湖縣",
            "金門縣",
            "連江縣",
          ],
          minBlocks: 1,
          maxBlocks: 3,
          locationPlaceholder: "路段或地點",
          reasonPlaceholder: "連續性不佳的原因",
        },
      ],
    },
    {
      id: "safety",
      title: "二、安全性",
      questions: [
        {
          id: "road-flatness",
          type: "radio",
          label: "行經路線的車道鋪面平整度",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "side-protection",
          type: "radio",
          label: "行經路線的車道路側防護設施(如：護欄、綠籬)",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "drainage-protection",
          type: "radio",
          label: "行經路線的車道路側排水溝蓋防護設施安全性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "riding-space",
          type: "radio",
          label: "行經路線的車道騎乘空間(如：寬度、型式)",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "intersection-safety",
          type: "radio",
          label: "穿越路口的安全性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "bridge-expansion-joint",
          type: "radio",
          label: "行經路線橋梁伸縮縫設施的安全性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "lighting",
          type: "radio",
          label: "行經隧道或陰暗處的照明設備",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "overall-safety",
          type: "radio",
          label: "本路線整體騎乘空間的安全性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "safety-issue",
          type: "region-long-answer",
          label: "您對騎乘路線感到安全性不佳的路段或地點及其原因為何？（非必填）",
          regions: [
            "新北市",
            "宜蘭縣",
            "花蓮縣",
            "臺東縣",
            "基隆市",
            "臺北市",
            "桃園市",
            "苗栗縣",
            "新竹縣",
            "新竹市",
            "臺中市",
            "彰化縣",
            "雲林縣",
            "南投縣",
            "嘉義縣",
            "嘉義市",
            "臺南市",
            "高雄市",
            "屏東縣",
            "澎湖縣",
            "金門縣",
            "連江縣",
          ],
          minBlocks: 1,
          maxBlocks: 3,
          locationPlaceholder: "路段或地點",
          reasonPlaceholder: "安全性不佳的原因",
        },
      ],
    },
    {
      id: "convenience",
      title: "三、便利性",
      questions: [
        {
          id: "supply-guide",
          type: "radio",
          label: "補給站導引指示及里程資訊",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "supply-density",
          type: "radio",
          label: "補給站設置密度",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "supply-service",
          type: "radio",
          label: "補給站服務項目",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "repair-post-location",
          type: "radio",
          label: "維修椿設置位置",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "repair-tools",
          type: "radio",
          label: "維修椿提供之維修工具",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意", "無使用本項目"],
        },
        {
          id: "service-info",
          type: "radio",
          label: "沿途自行車路線服務資訊提供的滿意度",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "overall-convenience",
          type: "radio",
          label: "本路線沿途自行車服務設施的便利性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "convenience-issue",
          type: "region-long-answer",
          label: "您對沿途自行車服務設施的便利性感到不佳的路段或地點及其原因為何？（非必填）",
          regions: [
            "新北市",
            "宜蘭縣",
            "花蓮縣",
            "臺東縣",
            "基隆市",
            "臺北市",
            "桃園市",
            "苗栗縣",
            "新竹縣",
            "新竹市",
            "臺中市",
            "彰化縣",
            "雲林縣",
            "南投縣",
            "嘉義縣",
            "嘉義市",
            "臺南市",
            "高雄市",
            "屏東縣",
            "澎湖縣",
            "金門縣",
            "連江縣",
          ],
          minBlocks: 1,
          maxBlocks: 3,
          locationPlaceholder: "路段或地點",
          reasonPlaceholder: "便利性不佳的原因",
        },
      ],
    },
    {
      id: "environment",
      title: "四、騎乘環境",
      questions: [
        {
          id: "environment-air-quality",
          type: "radio",
          label: "沿線的空氣品質",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "environment-shade-ratio",
          type: "radio",
          label: "沿線的綠蔭比例",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "environment-comfort",
          type: "radio",
          label: "本路線整體騎乘環境之舒適性",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "environment-issue",
          type: "region-long-answer",
          label: "您對騎乘環境感到舒適性不佳的路段或地點及其原因為何？（非必填）",
          regions: [
            "新北市",
            "宜蘭縣",
            "花蓮縣",
            "臺東縣",
            "基隆市",
            "臺北市",
            "桃園市",
            "苗栗縣",
            "新竹縣",
            "新竹市",
            "臺中市",
            "彰化縣",
            "雲林縣",
            "南投縣",
            "嘉義縣",
            "嘉義市",
            "臺南市",
            "高雄市",
            "屏東縣",
            "澎湖縣",
            "金門縣",
            "連江縣",
          ],
          minBlocks: 1,
          maxBlocks: 3,
          locationPlaceholder: "路段或地點",
          reasonPlaceholder: "舒適性不佳的原因",
        },
      ],
    },
    {
      id: "overall-satisfaction-gender",
      title: "五、整體體驗與性別友善",
      questions: [
        {
          id: "overall-satisfaction",
          type: "radio",
          label: "您對於本路線的整體騎乘體驗滿意程度為？",
          required: true,
          options: ["很不滿意", "不太滿意", "尚可", "還算滿意", "非常滿意"],
        },
        {
          id: "overall-satisfaction-reason",
          type: "radio-text",
          label: "您認為本路線的各項設施，是否存在性別差異而導致使用不便之處？",
          required: true,
          options: [
            {
              value: "無",
              label: "無",
            },
            {
              value: "有",
              label: "有",
              hasTextInput: true,
              textLabel: "設施描述",
              textPlaceholder: "請簡單說明是何種設施...",
            },
          ],
        },
        {
          id: "overall-gender-advise",
          type: "textarea",
          label: "從性別差異的角度來看，您認為在推廣自行車活動方面可以增添哪些服務或改進建議：",
          required: true,
        },
      ],
    },
  ],
}
