#!/bin/bash

# Firestore Index Creation Script
# This script creates the necessary composite indexes for the enhanced profile service

echo "🔥 Creating Firestore Indexes for Enhanced Profile Service..."
echo "📋 Please create the following composite indexes in Firebase Console:"
echo ""

echo "1. questionnaire_responses collection:"
echo "   - userId (Ascending)"
echo "   - submittedAt (Descending)"
echo "   - __name__ (Ascending)"
echo ""
echo "   Link: https://console.firebase.google.com/v1/r/project/velo-trace/firestore/indexes?create_composite=Clpwcm9qZWN0cy92ZWxvLXRyYWNlL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9xdWVzdGlvbm5haXJlX3Jlc3BvbnNlcy9pbmRleGVzL18QARoKCgZ1c2VySWQQARoPCgtzdWJtaXR0ZWRBdBACGgwKCF9fbmFtZV9fEAI"
echo ""

echo "2. questionnaire_responses collection (for questionnaire analytics):"
echo "   - questionnaireId (Ascending)"
echo "   - status (Ascending)"
echo "   - submittedAt (Descending)"
echo ""

echo "3. user_stats collection:"
echo "   - userId (Ascending)"
echo "   - updatedAt (Descending)"
echo ""

echo "4. users collection:"
echo "   - role (Ascending)"
echo "   - createdAt (Descending)"
echo ""

echo "📝 Firestore Index Rules (add to firestore.indexes.json):"
echo "{"
echo "  \"indexes\": ["
echo "    {"
echo "      \"collectionGroup\": \"questionnaire_responses\","
echo "      \"queryScope\": \"COLLECTION\","
echo "      \"fields\": ["
echo "        {"
echo "          \"fieldPath\": \"userId\","
echo "          \"order\": \"ASCENDING\""
echo "        },"
echo "        {"
echo "          \"fieldPath\": \"submittedAt\","
echo "          \"order\": \"DESCENDING\""
echo "        }"
echo "      ]"
echo "    },"
echo "    {"
echo "      \"collectionGroup\": \"questionnaire_responses\","
echo "      \"queryScope\": \"COLLECTION\","
echo "      \"fields\": ["
echo "        {"
echo "          \"fieldPath\": \"questionnaireId\","
echo "          \"order\": \"ASCENDING\""
echo "        },"
echo "        {"
echo "          \"fieldPath\": \"status\","
echo "          \"order\": \"ASCENDING\""
echo "        },"
echo "        {"
echo "          \"fieldPath\": \"submittedAt\","
echo "          \"order\": \"DESCENDING\""
echo "        }"
echo "      ]"
echo "    },"
echo "    {"
echo "      \"collectionGroup\": \"user_stats\","
echo "      \"queryScope\": \"COLLECTION\","
echo "      \"fields\": ["
echo "        {"
echo "          \"fieldPath\": \"userId\","
echo "          \"order\": \"ASCENDING\""
echo "        },"
echo "        {"
echo "          \"fieldPath\": \"updatedAt\","
echo "          \"order\": \"DESCENDING\""
echo "        }"
echo "      ]"
echo "    }"
echo "  ]"
echo "}"
echo ""

echo "✅ After creating indexes, run: npm run dev"
echo "⏳ Note: Indexes may take a few minutes to build"
